### ISSUE TITLE
Debug is always false on iOS

### ISSUE THREAD

**Issue by PhilHuot** [ozexpert/cordova-plugin-device-meta#5]
To reproduce the bug:

cordova run ios --debug 
or
cordova run ios --release

Both build are flagged as debug false.

I tested on iPhone 9.3 simulator and on a real 10.2 device.

**Comment by ucsbricks** [comment]
Any news on this issue? We still see it with Cordova 9.0, Cordova iOS SDK 5.0.1 and XCode 11.

**Comment by ozexpert** [comment]
Sorry i no longer maintain this repo. Feel free to fork it or create PR

**Comment by ucsbricks** [comment]
Fixed w/ Cordova 9.0.0, Cordova iOS SDK 5.1.1 and XCode 11.4. Maybe iOS SDK or XCode was the source of this problem. @ozexpert maybe you could close the issue? Thanks.
